const SOURCE_NRL='https://raw.githubusercontent.com/uselessnrlstats/uselessnrlstats/main/data/nrl';
const SOURCE_ORIGIN='https://raw.githubusercontent.com/uselessnrlstats/uselessnrlstats/main/cleaned_data/origin';
const CACHE_VERSION='ll-v23-2026-09-11';
const PREBUILT_URL='data/league-links.json.gz?v=23';
const NRL_YEARS=Array.from({length:19},(_,i)=>2008+i);

const COMPETITIONS=[
 {id:'NRL',name:'NRL',status:'live',years:'2008–2026',short:'NRL'},
 {id:'State of Origin',name:'State of Origin',status:'live',years:'2008–2026',short:'Origin'},
 {id:'NSW Cup',name:'NSW Cup',status:'building',years:'2008–2026',short:'NSW Cup'},
 {id:'Queensland Cup',name:'Queensland Cup',status:'building',years:'2008–2026',short:'Qld Cup'},
 {id:'NYC / Jersey Flegg',name:'NYC / Jersey Flegg',status:'building',years:'2008–2026',short:'Youth'},
 {id:'SG Ball',name:'SG Ball Cup',status:'building',years:'U18 / U19',short:'SG Ball'},
 {id:'Harold Matthews',name:'Harold Matthews Cup',status:'building',years:'U17 era',short:'Harold Matts'},
 {id:'Mal Meninga',name:'Mal Meninga Cup',status:'building',years:'U18 / U19',short:'Mal Meninga'},
 {id:'Cyril Connell',name:'Cyril Connell Cup',status:'building',years:'U17 from 2024',short:'Cyril Connell'},
 {id:'Queensland Colts',name:'Queensland Colts / U20 / U21',status:'building',years:'Historic pathway',short:'Qld Colts'},
 {id:'Other representative',name:'Other representative teams',status:'building',years:'Senior + U17+',short:'Representative'}
];

const state={
 players:new Map(),edges:new Map(),adj:new Map(),historyByPair:new Map(),
 rosters:new Map(),career:new Map(),appearances:new Map(),playerYears:new Map(),
 competitionsLoaded:new Set(),selectedPlayer:null,ledgerLimit:50,ledgerTab:'ledger',
 connectA:null,connectB:null,loaded:false,builtAt:null
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>Number(n||0).toLocaleString('en-AU');
const pairKey=(a,b)=>Number(a)<Number(b)?`${a}|${b}`:`${b}|${a}`;
const initials=name=>(name||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function titleCase(s){return (s||'').toLowerCase().replace(/(^|[\s\-'])\p{L}/gu,m=>m.toUpperCase()).replace(/\bMc([a-z])/g,(_,c)=>'Mc'+c.toUpperCase())}
function playerNameFromComma(raw){if(!raw)return'Unknown player';const i=raw.indexOf(',');if(i<0)return titleCase(raw);return `${titleCase(raw.slice(i+1).trim())} ${titleCase(raw.slice(0,i).trim())}`.trim()}
function canonicalTeam(raw){const s=(raw||'').replace(/\r/g,' ').replace(/\n/g,' ').replace(/\s+/g,' ').trim(),u=s.toUpperCase();const rules=[['CANBERRA','Canberra Raiders'],['BRISBANE','Brisbane Broncos'],['CANTERBURY','Canterbury-Bankstown Bulldogs'],['CRONULLA','Cronulla-Sutherland Sharks'],['GOLD COAST','Gold Coast Titans'],['MANLY','Manly Warringah Sea Eagles'],['MELBOURNE','Melbourne Storm'],['NEWCASTLE','Newcastle Knights'],['NORTH QUEENSLAND','North Queensland Cowboys'],['PARRAMATTA','Parramatta Eels'],['PENRITH','Penrith Panthers'],['SOUTH SYDNEY','South Sydney Rabbitohs'],['ST GEORGE','St George Illawarra Dragons'],['SYDNEY ROOSTERS','Sydney Roosters'],['ROOSTERS','Sydney Roosters'],['WESTS','Wests Tigers'],['NEW ZEALAND','New Zealand Warriors'],['WARRIORS','New Zealand Warriors'],['DOLPHINS','Dolphins']];for(const [needle,name] of rules)if(u.includes(needle))return name;return titleCase(s)}
function parseCSV(text){const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'){if(text[i+1]==='"'){field+='"';i++}else q=false}else field+=c}else{if(c==='"')q=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=''}else if(c!=='\r')field+=c}}if(field.length||row.length){row.push(field);rows.push(row)}return rows}
function headers(rows){const h={};(rows[0]||[]).forEach((v,i)=>h[v.trim()]=i);return h}
function setProgress(p,msg){$('#progressBar').style.width=`${Math.max(4,Math.min(100,p))}%`;$('#loadStatus').textContent=msg}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),1800)}
async function fetchText(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.text()}
async function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open('league-links',2);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('cache'))q.result.createObjectStore('cache')};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function cacheGet(){try{const db=await openDB();return await new Promise((res,rej)=>{const tx=db.transaction('cache','readonly'),q=tx.objectStore('cache').get(CACHE_VERSION);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}catch{return null}}
async function cachePut(payload){try{const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction('cache','readwrite');tx.objectStore('cache').put(payload,CACHE_VERSION);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}catch(e){console.warn('cache write',e)}}
async function clearCache(){try{const db=await openDB();await new Promise((res,rej)=>{const tx=db.transaction('cache','readwrite');tx.objectStore('cache').clear();tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}catch{}}
function careerKey(comp,team){return `${comp}|||${team}`}
function splitCareerKey(key){const [competition,...rest]=key.split('|||');return{competition,team:rest.join('|||')}}
function addCareer(pid,year,competition,team,n=1){pid=String(pid);year=Number(year);if(!state.career.has(pid))state.career.set(pid,new Map());const ym=state.career.get(pid);if(!ym.has(year))ym.set(year,new Map());const k=careerKey(competition,team);ym.get(year).set(k,(ym.get(year).get(k)||0)+n);const span=state.playerYears.get(pid)||{first:year,last:year};span.first=Math.min(span.first,year);span.last=Math.max(span.last,year);state.playerYears.set(pid,span);state.competitionsLoaded.add(competition)}
function addGroup(year,competition,team,ids){const rk=`${competition}|${year}|${team}`;if(!state.rosters.has(rk))state.rosters.set(rk,new Map());const rm=state.rosters.get(rk);for(const pid of ids){rm.set(pid,(rm.get(pid)||0)+1);state.appearances.set(pid,(state.appearances.get(pid)||0)+1);addCareer(pid,year,competition,team,1)}for(let a=0;a<ids.length;a++)for(let b=a+1;b<ids.length;b++){const x=ids[a],y=ids[b],pk=pairKey(x,y);let e=state.edges.get(pk);if(!e)e={a:Number(x)<Number(y)?x:y,b:Number(x)<Number(y)?y:x,games:0,first:year,last:year};e.games++;e.first=Math.min(e.first,year);e.last=Math.max(e.last,year);state.edges.set(pk,e);if(!state.historyByPair.has(pk))state.historyByPair.set(pk,new Map());const hm=state.historyByPair.get(pk),hk=`${year}|${competition}|${team}`,hv=hm.get(hk)||{year,competition,team,games:0};hv.games++;hm.set(hk,hv)}}
function processNrlSeason(rows,year){const h=headers(rows),groups=new Map();for(let i=1;i<rows.length;i++){const r=rows[i],pid=(r[h.player_id]||'').trim(),match=(r[h.match_id]||'').trim();if(!pid||!match)continue;const team=canonicalTeam(r[h.team]),key=`${match}|${team}`;if(!groups.has(key))groups.set(key,{team,players:new Set()});groups.get(key).players.add(pid)}for(const g of groups.values())addGroup(year,'NRL',g.team,[...g.players])}
function processOrigin(matchRows,playerRows){const mh=headers(matchRows),years=new Map();for(let i=1;i<matchRows.length;i++){const r=matchRows[i],id=(r[mh.match_id]||'').trim(),year=Number(r[mh.year]);if(id&&year)years.set(id,year)}const ph=headers(playerRows),groups=new Map();for(let i=1;i<playerRows.length;i++){const r=playerRows[i],pid=(r[ph.player_id]||'').trim(),match=(r[ph.match_id]||'').trim(),year=years.get(match);if(!pid||!match||!year||year<2008)continue;const team=titleCase((r[ph.team]||'').trim()),key=`${match}|${team}`;if(!groups.has(key))groups.set(key,{year,team,players:new Set()});groups.get(key).players.add(pid)}for(const g of groups.values())addGroup(g.year,'State of Origin',g.team,[...g.players])}
function buildAdj(){state.adj.clear();for(const e of state.edges.values()){if(!state.adj.has(e.a))state.adj.set(e.a,[]);if(!state.adj.has(e.b))state.adj.set(e.b,[]);state.adj.get(e.a).push({id:e.b,games:e.games,first:e.first,last:e.last});state.adj.get(e.b).push({id:e.a,games:e.games,first:e.first,last:e.last})}for(const arr of state.adj.values())arr.sort((a,b)=>b.games-a.games)}
function snapshot(){const career=[];for(const [id,ym] of state.career)for(const [year,tm] of ym)for(const [key,games] of tm){const{competition,team}=splitCareerKey(key);career.push([id,year,competition,team,games])}const rosters=[];for(const [key,rm] of state.rosters){const [competition,year,...rest]=key.split('|'),team=rest.join('|');for(const [id,games] of rm)rosters.push([competition,year,team,id,games])}const histories=[];for(const [pk,hm] of state.historyByPair)for(const hv of hm.values())histories.push([pk,hv.year,hv.competition,hv.team,hv.games]);return{version:23,players:[...state.players.values()].filter(p=>state.appearances.has(String(p.id))),edges:[...state.edges.values()],career,rosters,histories,appearances:[...state.appearances],competitionsLoaded:[...state.competitionsLoaded],builtAt:state.builtAt||Date.now()}}
function restore(s){state.players=new Map((s.players||[]).map(p=>[String(p.id),p]));state.edges=new Map();for(const e of s.edges||[])state.edges.set(pairKey(e.a,e.b),e);state.career=new Map();state.playerYears=new Map();state.competitionsLoaded=new Set(s.competitionsLoaded||[]);for(const [id,year,competition,team,games] of s.career||[])addCareer(String(id),Number(year),competition,team,Number(games));state.rosters=new Map();for(const [competition,year,team,id,games] of s.rosters||[]){const k=`${competition}|${year}|${team}`;if(!state.rosters.has(k))state.rosters.set(k,new Map());state.rosters.get(k).set(String(id),Number(games))}state.historyByPair=new Map();for(const [pk,year,competition,team,games] of s.histories||[]){if(!state.historyByPair.has(pk))state.historyByPair.set(pk,new Map());state.historyByPair.get(pk).set(`${year}|${competition}|${team}`,{year:Number(year),competition,team,games:Number(games)})}state.appearances=new Map((s.appearances||[]).map(([id,n])=>[String(id),Number(n)]));state.builtAt=s.builtAt||null;buildAdj()}
async function tryPrepared(){try{const r=await fetch(PREBUILT_URL,{cache:'no-cache'});if(!r.ok||!('DecompressionStream'in window))return false;const stream=r.body.pipeThrough(new DecompressionStream('gzip')),text=await new Response(stream).text(),payload=JSON.parse(text);if(!payload||payload.version!==23)return false;restore(payload);return true}catch(e){console.info('prepared data unavailable',e);return false}}
async function loadData(){setProgress(5,'Checking the latest League Links data…');if(await tryPrepared()){setProgress(100,'Ready');return}const cached=await cacheGet();if(cached){restore(cached);setProgress(100,'Ready');return}setProgress(10,'Loading player names…');const ps=parseCSV(await fetchText(`${SOURCE_NRL}/player_summary_data.csv`)),ph=headers(ps);for(let i=1;i<ps.length;i++){const r=ps[i],id=(r[ph.player_id]||'').trim();if(!id)continue;state.players.set(id,{id,name:playerNameFromComma(r[ph.player_name_comma]),birthday:(r[ph.player_birthday]||'').trim()})}let completed=0;await Promise.all(NRL_YEARS.map(async year=>{const idx=year-1907,txt=await fetchText(`${SOURCE_NRL}/player_match_data/player_match_data_${idx}.csv`);processNrlSeason(parseCSV(txt),year);completed++;setProgress(12+(completed/NRL_YEARS.length)*66,`Loading NRL seasons · ${completed} of ${NRL_YEARS.length}`)}));setProgress(80,'Adding State of Origin…');const [om,op]=await Promise.all([fetchText(`${SOURCE_ORIGIN}/match_data.csv`),fetchText(`${SOURCE_ORIGIN}/player_match_data.csv`)]);processOrigin(parseCSV(om),parseCSV(op));buildAdj();state.builtAt=Date.now();setProgress(92,'Saving for a faster next visit…');await cachePut(snapshot());setProgress(100,'Ready')}
function playerMeta(id){id=String(id);const p=state.players.get(id)||{id,name:`Player ${id}`,birthday:''},span=state.playerYears.get(id),cm=state.career.get(id);let latestTeam='Rugby league player',latestYear=-1;const comps=new Set(),teams=new Set();if(cm){for(const [year,tm] of cm)for(const key of tm.keys()){const{competition,team}=splitCareerKey(key);comps.add(competition);teams.add(`${competition}|${team}`);if(competition==='NRL'&&year>=latestYear){latestYear=year;latestTeam=team}}if(latestYear<0&&span&&cm.get(span.last)){const first=[...cm.get(span.last).keys()][0];if(first)latestTeam=splitCareerKey(first).team}}return{...p,span,latestTeam,appearances:state.appearances.get(id)||0,teammates:(state.adj.get(id)||[]).length,teams:teams.size,competitions:comps.size}}
function findPlayers(q,limit=9){q=(q||'').trim().toLowerCase();if(!q)return[];const starts=[],includes=[];for(const p of state.players.values()){if(!state.appearances.has(String(p.id)))continue;const n=p.name.toLowerCase();if(n.startsWith(q))starts.push(p);else if(n.includes(q))includes.push(p)}const rank=p=>state.appearances.get(String(p.id))||0;starts.sort((a,b)=>rank(b)-rank(a));includes.sort((a,b)=>rank(b)-rank(a));return starts.concat(includes).slice(0,limit)}
function loadedPlayerCount(){return[...state.appearances.keys()].filter(id=>state.players.has(String(id))).length}
function availableCompetitionIds(){return[...state.competitionsLoaded].sort((a,b)=>a==='NRL'?-1:b==='NRL'?1:a.localeCompare(b))}
function competitionShort(id){return COMPETITIONS.find(c=>c.id===id)?.short||id}
