const TEAM_DIRECTORY={
 'NRL':{season:2026,teams:['Brisbane Broncos','Canberra Raiders','Canterbury-Bankstown Bulldogs','Cronulla-Sutherland Sharks','Dolphins','Gold Coast Titans','Manly Warringah Sea Eagles','Melbourne Storm','Newcastle Knights','New Zealand Warriors','North Queensland Cowboys','Parramatta Eels','Penrith Panthers','South Sydney Rabbitohs','St George Illawarra Dragons','Sydney Roosters','Wests Tigers']},
 'State of Origin':{season:2026,teams:['New South Wales','Queensland']},
 'International':{season:2026,teams:['Australia','Cook Islands','England','Fiji','France','Ireland','Lebanon','New Zealand','Papua New Guinea','Samoa','Scotland','Tonga','Wales']},
 'NSW Cup':{season:2026,teams:['Canberra Raiders','Canterbury-Bankstown Bulldogs','Manly Warringah Sea Eagles','Melbourne Storm','Newcastle Knights','New Zealand Warriors','Newtown Jets','North Sydney Bears','Parramatta Eels','Penrith Panthers','South Sydney Rabbitohs','St George Illawarra Dragons','Sydney Roosters','Western Suburbs Magpies']},
 'Queensland Cup':{season:2026,teams:['Brisbane Tigers','Burleigh Bears','Central Queensland Capras','Ipswich Jets','Mackay Cutters','Northern Pride','Norths Devils','Papua New Guinea Hunters','Redcliffe Dolphins','Souths Logan Magpies','Sunshine Coast Falcons','Townsville Blackhawks','Tweed Seagulls','Western Clydesdales','Wynnum Manly Seagulls']},
 'NYC / Jersey Flegg':{season:2026,teams:['Canberra Raiders','Canterbury-Bankstown Bulldogs','Cronulla-Sutherland Sharks','Kaiviti Silktails','Manly Warringah Sea Eagles','Melbourne Storm','Newcastle Knights','New Zealand Warriors','Parramatta Eels','Penrith Panthers','South Sydney Rabbitohs','St George Illawarra Dragons','Sydney Roosters','Wests Tigers']},
 'SG Ball':{season:2026,teams:['Balmain Tigers','Canberra Raiders','Canterbury-Bankstown Bulldogs','Central Coast Roosters','Cronulla-Sutherland Sharks','Illawarra Steelers','Manly Warringah Sea Eagles','Melbourne Storm','Newcastle Knights','New Zealand Warriors','North Sydney Bears','Parramatta Eels','Penrith Panthers','South Sydney Rabbitohs','St George Dragons','Sydney Roosters','Western Suburbs Magpies']},
 'Harold Matthews':{season:2026,teams:['Balmain Tigers','Canberra Raiders','Canterbury-Bankstown Bulldogs','Central Coast Roosters','Cronulla-Sutherland Sharks','Illawarra Steelers','Manly Warringah Sea Eagles','Melbourne Storm','Newcastle Knights','New Zealand Warriors','North Sydney Bears','Parramatta Eels','Penrith Panthers','South Sydney Rabbitohs','St George Dragons','Sydney Roosters','Western Suburbs Magpies']},
 'Mal Meninga':{season:2026,teams:['Brisbane Tigers','Burleigh Bears','Central Queensland Capras','Ipswich Jets','Mackay Cutters','Northern Pride','Norths Devils','Redcliffe Dolphins','Souths Logan Magpies','Sunshine Coast Falcons','Townsville Blackhawks','Tweed Seagulls','Western Clydesdales','Wynnum Manly Seagulls']},
 'Cyril Connell':{season:2026,teams:['Brisbane Tigers','Burleigh Bears','Central Queensland Capras','Ipswich Jets','Mackay Cutters','Northern Pride','Norths Devils','Redcliffe Dolphins','Souths Logan Magpies','Sunshine Coast Falcons','Townsville Blackhawks','Tweed Seagulls','Western Clydesdales','Western Mustangs Bulls','Wynnum Manly Seagulls']}
};
function applyV25Copy(){
 const cov=document.querySelector('.coverage');if(cov){const s=cov.querySelector('strong'),sm=cov.querySelector('small');if(s)s.textContent='U17 pathways to internationals';if(sm)sm.textContent='Building match history from 2000 onward'}
 const ver=document.querySelector('.sidefoot span:first-child');if(ver)ver.textContent='v0.25';
 const pill=document.querySelector('.pill');if(pill)pill.innerHTML='<i></i> U17 pathways · state cups · NRL · internationals';
 const hero=document.querySelector('.herocopy p');if(hero)hero.textContent='Explore rugby league careers from U17 pathways through state cups, NRL, Origin and international football. Match-by-match history is being built from 2000 onward.';
 const stats=document.querySelectorAll('.stat span');if(stats[3])stats[3].textContent='Competition areas mapped';
 const teamsIntro=document.querySelector('#view-teams .sectionhead p');if(teamsIntro)teamsIntro.textContent='Choose a competition and team. Confirmed match records appear as each historical layer is added.';
 const compHead=document.querySelector('#view-competitions .sectionhead h1');if(compHead)compHead.textContent='From U17 pathways to internationals.';
 const compIntro=document.querySelector('#view-competitions .sectionhead p');if(compIntro)compIntro.textContent='League Links is building one connected record of every team and player from U17 pathways through state cups, NRL, Origin and international football, from 2000 onward where reliable records exist.';
 const notes=document.querySelectorAll('#view-competitions .simple-note');if(notes[1]){const h=notes[1].querySelector('h3'),p=notes[1].querySelector('p');if(h)h.textContent='Building the database';if(p)p.textContent='Teams are mapped first, then player appearances are added match by match. NSW Cup and Queensland Cup are the next major player-history layers, followed by Jersey Flegg and NYC, SG Ball, Harold Matthews in U17+ seasons, Mal Meninga, Cyril Connell, Queensland Colts and other representative football.'}
}
function relationshipComps(a,b){return[...new Set(histories(a,b).map(h=>competitionShort(h.competition)))]}
function shortestPath(start,end){start=String(start);end=String(end);if(start===end)return[start];const q=[start],prev=new Map([[start,null]]);for(let head=0;head<q.length;head++){const cur=q[head],neighbors=(state.adj.get(cur)||[]).slice().sort((a,b)=>b.games-a.games);for(const e of neighbors){if(prev.has(e.id))continue;prev.set(e.id,cur);if(e.id===end){const p=[end];let x=cur;while(x){p.push(x);x=prev.get(x)}return p.reverse()}q.push(e.id)}}return null}
function renderConnection(){if(!state.connectA||!state.connectB){$('#connectionResult').innerHTML='<div class="empty"><strong>Choose two players.</strong>We’ll show how they connect.</div>';return}const p=shortestPath(state.connectA,state.connectB);if(!p){$('#connectionResult').innerHTML='<div class="empty"><strong>No link found yet.</strong>The competitions currently in League Links do not connect these two players.</div>';return}let html='<div class="pathline">';p.forEach((id,i)=>{html+=`<button class="nodebtn" data-path-player="${id}">${esc(playerMeta(id).name)}</button>`;if(i<p.length-1){const e=state.edges.get(pairKey(id,p[i+1])),hs=histories(id,p[i+1]),ys=[...new Set(hs.map(h=>h.year))],cs=relationshipComps(id,p[i+1]);html+=`<span class="edge"><b>${e?.games||0} games</b>${ys.length?`${Math.min(...ys)}–${Math.max(...ys)}`:''}<small>${esc(cs.join(' + '))}</small></span>`}});html+=`</div><div class="pathsummary"><span class="badge"><b>${p.length-1}</b> link${p.length-1===1?'':'s'}</span><span class="badge"><b>${p.length}</b> players</span><span class="badge">Shortest path currently available</span></div>`;$('#connectionResult').innerHTML=html;$$('[data-path-player]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.pathPlayer))}
$('#connectGo').onclick=()=>{if(state.connectA&&state.connectB)route('connect',{a:state.connectA,b:state.connectB});else toast('Choose both players first')}
function rosterKeysForCompetition(comp){return[...state.rosters.keys()].filter(k=>k.startsWith(`${comp}|`))}
function mappedCompetitionIds(){const live=new Set(availableCompetitionIds());Object.keys(TEAM_DIRECTORY).forEach(x=>live.add(x));live.add('International');return COMPETITIONS.map(c=>c.id).filter(id=>live.has(id))}
function fillCompetitionSelect(){const comps=mappedCompetitionIds();$('#teamCompetition').innerHTML=comps.map(c=>`<option>${esc(c)}</option>`).join('');fillTeamYears(comps[0]||'NRL')}
function fillTeamYears(comp,selected){if(comp==='International'){$('#teamYear').disabled=true;$('#teamYear').innerHTML='<option value="all">2000 onward</option>';fillTeams(comp,'all');return}$('#teamYear').disabled=false;const actual=[...new Set(rosterKeysForCompetition(comp).map(k=>Number(k.split('|')[1])))],cat=TEAM_DIRECTORY[comp],years=[...new Set([...actual,...(cat?[cat.season]:[])])].sort((a,b)=>b-a);$('#teamYear').innerHTML=years.map(y=>`<option value="${y}" ${String(y)===String(selected)?'selected':''}>${y}${y===2026?' · current':''}</option>`).join('');fillTeams(comp,$('#teamYear').value)}
function fillTeams(comp,year,selected){if(comp==='International'){const teams=[...new Set([...INTERNATIONAL_TEAMS,...(TEAM_DIRECTORY.International?.teams||[]),...state.teamCatalogues.keys()])].sort();$('#teamName').innerHTML=teams.map(t=>`<option ${t===selected?'selected':''}>${esc(t)}</option>`).join('');return}const prefix=`${comp}|${year}|`,actual=[...state.rosters.keys()].filter(k=>k.startsWith(prefix)).map(k=>k.slice(prefix.length)),cat=Number(year)===TEAM_DIRECTORY[comp]?.season?(TEAM_DIRECTORY[comp]?.teams||[]):[],teams=[...new Set([...actual,...cat])].sort();$('#teamName').innerHTML=teams.map(t=>`<option ${t===selected?'selected':''}>${esc(t)}</option>`).join('')}
$('#teamCompetition').onchange=()=>fillTeamYears($('#teamCompetition').value);$('#teamYear').onchange=()=>fillTeams($('#teamCompetition').value,$('#teamYear').value);$('#teamGo').onclick=()=>{renderRoster();route('teams',{competition:$('#teamCompetition').value,year:$('#teamYear').value||'all',team:$('#teamName').value})}
function renderInternationalRoster(team){const cat=state.teamCatalogues.get(team),rows=(cat?.players||[]).slice().sort((a,b)=>(b.appearances||0)-(a.appearances||0)||(a.name||'').localeCompare(b.name||''));$('#teamMeta').innerHTML=`<div class="sectionhead" style="margin-top:26px"><div><h2>${esc(team)}</h2><p>Senior international team · player history from 2000 onward is being expanded.</p></div></div>`;if(!rows.length){$('#teamRoster').innerHTML='<div class="card empty" style="grid-column:1/-1"><strong>Team mapped.</strong>Its match-by-match player history is being added. Player-to-player links will only appear after individual match appearances are confirmed.</div>';return}$('#teamRoster').innerHTML=rows.map(r=>{const years=r.first||r.last?` · ${r.first||'?'}–${r.last||'?'}`:'',games=r.appearances?`${r.appearances} recorded international appearance${r.appearances===1?'':'s'}`:'Recorded international player';return r.id&&state.players.has(String(r.id))?`<button class="rostercard" data-roster-player="${r.id}"><strong>${esc(r.name)}</strong><small>${games}${years}</small></button>`:`<div class="rostercard roster-static"><strong>${esc(r.name)}</strong><small>${games}${years}</small></div>`}).join('');$$('[data-roster-player]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.rosterPlayer))}
function renderRoster(){const c=$('#teamCompetition').value,y=$('#teamYear').value,t=$('#teamName').value;if(c==='International'){renderInternationalRoster(t);return}const rm=state.rosters.get(`${c}|${y}|${t}`);if(!rm){const mapped=(TEAM_DIRECTORY[c]?.teams||[]).includes(t);$('#teamMeta').innerHTML=mapped?`<div class="sectionhead" style="margin-top:26px"><div><h2>${esc(t)} · ${esc(y)}</h2><p>${esc(c)} · team mapped</p></div></div>`:'';$('#teamRoster').innerHTML=mapped?'<div class="card empty" style="grid-column:1/-1"><strong>Team mapped.</strong>Match-by-match player records are being added. Once confirmed appearances are loaded, the players and their teammate links will appear here automatically.</div>':'<div class="card empty" style="grid-column:1/-1">No players found for that selection.</div>';return}const rows=[...rm.entries()].map(([id,games])=>({id,games,name:playerMeta(id).name})).sort((a,b)=>b.games-a.games||a.name.localeCompare(b.name));$('#teamMeta').innerHTML=`<div class="sectionhead" style="margin-top:26px"><div><h2>${esc(t)} · ${y}</h2><p>${esc(c)} · ${rows.length} players recorded in matches</p></div></div>`;$('#teamRoster').innerHTML=rows.map(r=>`<button class="rostercard" data-roster-player="${r.id}"><strong>${esc(r.name)}</strong><small>${r.games} game${r.games===1?'':'s'} · ${esc(c)}</small></button>`).join('');$$('[data-roster-player]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.rosterPlayer))}
function renderCompetitions(){const order=COMPETITIONS;$('#competitionGrid').innerHTML=order.map(c=>{const mapped=TEAM_DIRECTORY[c.id]?.teams?.length||0,copy=c.status==='live'?'Match-by-match player history is available now.':c.status==='catalogue'?'National teams are mapped and can be chosen now. Match-by-match player history is being expanded.':mapped?`${mapped} current teams are mapped. Match-by-match player history is being added.`:'Historical teams and player records are being added.';const label=c.status==='live'?'Match history live':c.status==='catalogue'?'Teams mapped':mapped?'Teams mapped':'Building';return`<article class="competition-card card"><h3>${esc(c.name)}</h3><p>${copy}</p><div class="meta"><span>${esc(c.years)}</span><span class="comp-status ${c.status}">${label}</span></div></article>`}).join('')}
function initUI(){const appTotal=[...state.appearances.values()].reduce((a,b)=>a+b,0);$('#sPlayers').textContent=fmt(loadedPlayerCount());$('#sEdges').textContent=fmt(state.edges.size);$('#sApps').textContent=fmt(appTotal);$('#sComps').textContent=fmt(COMPETITIONS.length);$('#dataStatus').textContent='Ready';$('#dataStatus').classList.add('ready');applyV25Copy();renderHomePeople();fillCompetitionSelect();renderRoster();renderCompetitions();setupAutocomplete($('#homeSearch'),$('#homeSuggestions'),id=>openPlayer(id));setupAutocomplete($('#ledgerSearch'),$('#ledgerSuggestions'),id=>openPlayer(id));setupAutocomplete($('#connectA'),$('#connectASuggestions'),id=>{state.connectA=id});setupAutocomplete($('#connectB'),$('#connectBSuggestions'),id=>{state.connectB=id});$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));$('#startExplore').onclick=()=>{$('#homeSearch').focus();$('#homeSearch').scrollIntoView({behavior:'smooth',block:'center'})};$('#globalSearchBtn').onclick=()=>{route('players');setTimeout(()=>$('#ledgerSearch').focus(),80)};applyRoute()}
(async()=>{try{await loadData();state.loaded=true;initUI();$('#loader').style.display='none'}catch(err){console.error(err);$('#loadStatus').innerHTML=`League Links could not load. <button class="ghost" onclick="location.reload()" style="margin-left:8px">Try again</button>`;$('#progressBar').style.width='100%';$('#progressBar').style.background='var(--red)'}})()
