const LL_COMPETITION_ORDER=COMPETITIONS.map(c=>c.id);
function competitionRank(id){const i=LL_COMPETITION_ORDER.indexOf(id);return i<0?999:i}
function orderedCompetitionIds(ids){return[...new Set(ids)].sort((a,b)=>competitionRank(a)-competitionRank(b)||String(a).localeCompare(String(b)))}
availableCompetitionIds=function(){return orderedCompetitionIds([...state.competitionsLoaded,'International'])};
relationshipComps=function(a,b){return orderedCompetitionIds(histories(a,b).map(h=>h.competition)).map(competitionShort)};

applyV25Copy=function(){
 const cov=document.querySelector('.coverage');if(cov){const s=cov.querySelector('strong'),sm=cov.querySelector('small');if(s)s.textContent='Rugby league history from 2000';if(sm)sm.textContent='Under-17 pathways through to internationals'}
 const ver=document.querySelector('.sidefoot span:first-child');if(ver)ver.textContent='v0.26';
 const pill=document.querySelector('.pill');if(pill)pill.innerHTML='<i></i> MATCH-BY-MATCH HISTORY · 2000 ONWARD';
 const heroH=document.querySelector('.herocopy h1');if(heroH)heroH.textContent='See where every career connects.';
 const hero=document.querySelector('.herocopy p');if(hero)hero.textContent='Search a player to explore teammates, opponents, clubs and connections across the game, from junior pathways to representative football.';
 const proof=document.querySelector('.proof');if(proof)proof.innerHTML='<span><b>✓</b>Teammates</span><span><b>✓</b>Opponents</span><span><b>✓</b>Shared seasons</span>';
 const stats=document.querySelectorAll('.stat span');if(stats[3])stats[3].textContent='Competition areas';
 const teamsIntro=document.querySelector('#view-teams .sectionhead p');if(teamsIntro)teamsIntro.textContent='Choose a competition, season and team. Match records and season player lists appear as each historical layer is added.';
 const compHead=document.querySelector('#view-competitions .sectionhead h1');if(compHead)compHead.textContent='Coverage across the game.';
 const compIntro=document.querySelector('#view-competitions .sectionhead p');if(compIntro)compIntro.textContent='League Links is building one connected record from under-17 pathways through state cups, NRL, Origin and international football, using the strongest records available for each season.';
 const notes=document.querySelectorAll('#view-competitions .simple-note');if(notes[1]){const h=notes[1].querySelector('h3'),p=notes[1].querySelector('p');if(h)h.textContent='How coverage grows';if(p)p.textContent='Teams are mapped first, season player records are added next, and teammate links are only created from confirmed match appearances. The database expands automatically as reliable historical records are added.'}
};

renderPlayer=function(id){
 id=String(id);const m=playerMeta(id),adj=state.adj.get(id)||[],fav=favIds().includes(id);$('#ledgerHeading').textContent=m.name;$('#ledgerIntro').textContent='Explore who they played with, who they faced most often, and where their recorded career took them.';
 $('#playerContent').innerHTML=`<div class="card playerhero"><div class="playerrow"><div class="playerid"><div class="avatar">${initials(m.name)}</div><div><h2>${esc(m.name)}</h2><p>${esc(m.latestTeam)}${m.span?` · ${m.span.first}–${m.span.last}`:''}</p></div></div><div class="playeractions"><button class="ghost" id="copyPlayer">Copy link</button><button class="iconbtn" id="favPlayer" title="Favourite">${fav?'★':'☆'}</button></div></div><div class="metrics"><div class="metric"><strong>${fmt(m.appearances)}</strong><span>Games recorded</span></div><div class="metric"><strong>${fmt(m.teammates)}</strong><span>Teammates</span></div><div class="metric"><strong>${m.span?m.span.last-m.span.first+1:0}</strong><span>Years covered</span></div><div class="metric"><strong>${fmt(m.competitions)}</strong><span>Competitions</span></div></div></div><div class="subtabs"><button class="subtab ${state.ledgerTab==='ledger'?'active':''}" data-subtab="ledger">Teammates</button><button class="subtab ${state.ledgerTab==='opponents'?'active':''}" data-subtab="opponents">Opponents</button><button class="subtab ${state.ledgerTab==='career'?'active':''}" data-subtab="career">Career</button></div><div id="playerSub"></div><aside class="ad-slot ad-inline" aria-label="Advertisement"><span>Advertisement</span><div><strong>Partner space</strong><small>A small ad here helps keep League Links free.</small></div></aside>`;
 $('#copyPlayer').onclick=()=>navigator.clipboard.writeText(location.href).then(()=>toast('Link copied'));$('#favPlayer').onclick=()=>toggleFav(id);$$('[data-subtab]').forEach(b=>b.onclick=()=>{state.ledgerTab=b.dataset.subtab;renderPlayer(id)});if(state.ledgerTab==='career')renderCareer(id);else if(state.ledgerTab==='opponents')renderOpponents(id);else renderLedger(id,adj)
};

renderLedger=function(id,adj){
 const m=playerMeta(id),start=m.span?.first||2000,end=m.span?.last||2026,compOptions=['All',...availableCompetitionIds().filter(x=>x!=='International')];$('#playerSub').innerHTML=`<div class="toolbar"><div class="field"><label>Find a teammate</label><input id="mateFilter" placeholder="Type a name…"></div><div class="field"><label>Competition</label><select id="mateComp">${compOptions.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>From</label><select id="mateFrom">${yearOptions(start,end,start)}</select></div><div class="field"><label>To</label><select id="mateTo">${yearOptions(start,end,end)}</select></div><button class="ghost" id="resetLedger">Reset</button></div><div id="ledgerTable"></div>`;
 const redraw=()=>{const q=$('#mateFilter').value.toLowerCase(),from=Number($('#mateFrom').value)||0,to=Number($('#mateTo').value)||9999,comp=$('#mateComp').value;let rows=adj.map(e=>({...e,name:playerMeta(e.id).name,g:filteredEdgeGames(id,e.id,from,to,comp)})).filter(e=>e.g>0&&e.name.toLowerCase().includes(q)).sort((a,b)=>b.g-a.g||a.name.localeCompare(b.name));const shown=rows.slice(0,state.ledgerLimit);$('#ledgerTable').innerHTML=`<div class="tablewrap"><table><thead><tr><th>#</th><th>Teammate</th><th>Games together</th><th>Years</th><th>Competitions</th><th></th></tr></thead><tbody>${shown.map((e,i)=>{const hs=histories(id,e.id).filter(h=>h.year>=from&&h.year<=to&&(comp==='All'||h.competition===comp)),ys=[...new Set(hs.map(h=>h.year))],cs=orderedCompetitionIds(hs.map(h=>h.competition)).map(competitionShort);return`<tr><td>${i+1}</td><td><button class="playerlink" data-open="${e.id}">${esc(e.name)}</button></td><td class="games">${e.g}</td><td class="yearspan">${ys.length?`${Math.min(...ys)}–${Math.max(...ys)}`:'—'}</td><td class="yearspan">${esc(cs.join(', ')||'—')}</td><td><button class="historybtn" data-history="${e.id}">Shared history</button></td></tr>`}).join('')}</tbody></table></div>${rows.length>shown.length?`<div class="loadmore"><button class="ghost" id="moreLedger">Show more · ${rows.length-shown.length} left</button></div>`:''}`;$$('[data-open]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.open));$$('[data-history]').forEach(b=>b.onclick=()=>openHistory(id,b.dataset.history));if($('#moreLedger'))$('#moreLedger').onclick=()=>{state.ledgerLimit+=50;redraw()}};
 $('#mateFilter').oninput=redraw;$('#mateComp').onchange=redraw;$('#mateFrom').onchange=redraw;$('#mateTo').onchange=redraw;$('#resetLedger').onclick=()=>{state.ledgerLimit=50;$('#mateFilter').value='';$('#mateComp').value='All';$('#mateFrom').value=start;$('#mateTo').value=end;redraw()};redraw()
};

async function renderOpponents(id){
 const m=playerMeta(id);$('#playerSub').innerHTML='<div class="card empty"><strong>Loading opponents…</strong></div>';const ok=await ensureOpponents();if(state.selectedPlayer!==String(id)||state.ledgerTab!=='opponents')return;if(!ok){$('#playerSub').innerHTML='<div class="card empty"><strong>Opponent history is unavailable right now.</strong>Try again shortly.</div>';return}
 const base=opponentRowsForPlayer(id),years=base.map(r=>r.year),start=years.length?Math.min(...years):(m.span?.first||2000),end=years.length?Math.max(...years):(m.span?.last||2026),compOptions=['All',...orderedCompetitionIds(base.map(r=>r.competition))];
 $('#playerSub').innerHTML=`<div class="toolbar"><div class="field"><label>Find an opponent</label><input id="oppFilter" placeholder="Type a team…"></div><div class="field"><label>Competition</label><select id="oppComp">${compOptions.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>From</label><select id="oppFrom">${yearOptions(start,end,start)}</select></div><div class="field"><label>To</label><select id="oppTo">${yearOptions(start,end,end)}</select></div><button class="ghost" id="resetOpp">Reset</button></div><div id="opponentTable"></div>`;
 const redraw=()=>{const q=$('#oppFilter').value.toLowerCase(),from=Number($('#oppFrom').value)||0,to=Number($('#oppTo').value)||9999,comp=$('#oppComp').value,agg=new Map();for(const r of base){if(r.year<from||r.year>to||(comp!=='All'&&r.competition!==comp))continue;const k=r.opponent,v=agg.get(k)||{opponent:k,games:0,years:new Set(),competitions:new Set()};v.games+=r.games;v.years.add(r.year);v.competitions.add(r.competition);agg.set(k,v)}let rows=[...agg.values()].filter(r=>r.opponent.toLowerCase().includes(q)).sort((a,b)=>b.games-a.games||a.opponent.localeCompare(b.opponent));$('#opponentTable').innerHTML=`<div class="tablewrap"><table><thead><tr><th>#</th><th>Opponent</th><th>Games against</th><th>Years</th><th>Competitions</th></tr></thead><tbody>${rows.map((r,i)=>{const ys=[...r.years],cs=orderedCompetitionIds([...r.competitions]).map(competitionShort);return`<tr><td>${i+1}</td><td><strong>${esc(r.opponent)}</strong></td><td class="games">${r.games}</td><td class="yearspan">${ys.length?`${Math.min(...ys)}–${Math.max(...ys)}`:'—'}</td><td class="yearspan">${esc(cs.join(', ')||'—')}</td></tr>`}).join('')}</tbody></table></div>${rows.length?'':'<div class="card empty"><strong>No opponents found for those filters.</strong></div>'}`};
 $('#oppFilter').oninput=redraw;$('#oppComp').onchange=redraw;$('#oppFrom').onchange=redraw;$('#oppTo').onchange=redraw;$('#resetOpp').onclick=()=>{$('#oppFilter').value='';$('#oppComp').value='All';$('#oppFrom').value=start;$('#oppTo').value=end;redraw()};redraw()
}

renderCareer=function(id){const ym=state.career.get(id);if(!ym){$('#playerSub').innerHTML='<div class="card empty">No games loaded yet.</div>';return}const rows=[];for(const[year,tm]of[...ym.entries()].sort((a,b)=>b[0]-a[0]))for(const[key,games]of tm.entries()){const{competition,team}=splitCareerKey(key);rows.push({year,competition,team,games})}rows.sort((a,b)=>b.year-a.year||competitionRank(a.competition)-competitionRank(b.competition)||a.team.localeCompare(b.team));$('#playerSub').innerHTML=`<div class="timeline">${rows.map(r=>`<div class="seasonrow"><div class="year">${r.year}</div><div class="club">${esc(r.team)}<small>${esc(r.competition)}</small></div><div class="count">${r.games} game${r.games===1?'':'s'}</div></div>`).join('')}</div>`};

openHistory=function(a,b){const A=playerMeta(a),B=playerMeta(b),hs=histories(a,b);if(!hs.length)return;const total=hs.reduce((s,h)=>s+h.games,0),years=[...new Set(hs.map(h=>h.year))],max=Math.max(...hs.map(h=>h.games)),ordered=[...hs].sort((x,y)=>y.year-x.year||competitionRank(x.competition)-competitionRank(y.competition)||x.team.localeCompare(y.team));$('#drawer').innerHTML=`<div class="drawerhead"><div><p class="eyebrow">SHARED HISTORY</p><h2>${esc(A.name)} × ${esc(B.name)}</h2><p>Games where both players were recorded for the same team.</p></div><button class="iconbtn" id="closeDrawer">×</button></div><div class="sharedstats"><div class="sharedstat"><strong>${total}</strong><span>Games together</span></div><div class="sharedstat"><strong>${years.length}</strong><span>Shared years</span></div><div class="sharedstat"><strong>${Math.min(...years)}–${Math.max(...years)}</strong><span>Shared span</span></div></div><div class="bars">${ordered.map(h=>`<div class="barrow"><div class="yr">${h.year}</div><div class="bar"><i style="width:${Math.max(6,h.games/max*100)}%"></i></div><div class="n">${h.games}</div><div class="barclub">${esc(h.team)} · ${esc(competitionShort(h.competition))}</div></div>`).join('')}</div><div class="heroactions" style="margin-top:22px"><button class="ghost" data-drawer-player="${a}">Open ${esc(A.name)}</button><button class="primary" data-drawer-player="${b}">Open ${esc(B.name)}</button></div>`;$('#drawerBack').classList.add('show');$('#closeDrawer').onclick=closeDrawer;$$('[data-drawer-player]').forEach(x=>x.onclick=()=>{closeDrawer();openPlayer(x.dataset.drawerPlayer)})};

fillTeamYears=function(comp,selected){if(comp==='International'){$('#teamYear').disabled=true;$('#teamYear').innerHTML='<option value="all">2000 onward</option>';fillTeams(comp,'all');return}$('#teamYear').disabled=false;const actual=[...new Set(rosterKeysForCompetition(comp).map(k=>Number(k.split('|')[1])))],catalogue=[...new Set(catalogueKeysForCompetition(comp).map(k=>Number(k.split('|')[1])))],cat=TEAM_DIRECTORY[comp],years=[...new Set([...actual,...catalogue,...(cat?[cat.season]:[])])].sort((a,b)=>b-a);$('#teamYear').innerHTML=years.map(y=>`<option value="${y}" ${String(y)===String(selected)?'selected':''}>${y}${y===2026?' · current':''}</option>`).join('');fillTeams(comp,$('#teamYear').value)};
fillTeams=function(comp,year,selected){if(comp==='International'){const teams=[...new Set([...INTERNATIONAL_TEAMS,...(TEAM_DIRECTORY.International?.teams||[]),...state.teamCatalogues.keys()])].sort();$('#teamName').innerHTML=teams.map(t=>`<option ${t===selected?'selected':''}>${esc(t)}</option>`).join('');return}const prefix=`${comp}|${year}|`,actual=[...state.rosters.keys()].filter(k=>k.startsWith(prefix)).map(k=>k.slice(prefix.length)),catalogue=[...state.seasonCatalogues.keys()].filter(k=>k.startsWith(prefix)).map(k=>k.slice(prefix.length)),cat=Number(year)===TEAM_DIRECTORY[comp]?.season?(TEAM_DIRECTORY[comp]?.teams||[]):[],teams=[...new Set([...actual,...catalogue,...cat])].sort();$('#teamName').innerHTML=teams.map(t=>`<option ${t===selected?'selected':''}>${esc(t)}</option>`).join('')};

renderRoster=function(){const c=$('#teamCompetition').value,y=$('#teamYear').value,t=$('#teamName').value;if(c==='International'){renderInternationalRoster(t);return}const key=`${c}|${y}|${t}`,rm=state.rosters.get(key),catalogue=state.seasonCatalogues.get(key)||[];if(rm){const rows=[...rm.entries()].map(([id,games])=>({id,games,name:playerMeta(id).name})).sort((a,b)=>b.games-a.games||a.name.localeCompare(b.name));$('#teamMeta').innerHTML=`<div class="sectionhead" style="margin-top:26px"><div><h2>${esc(t)} · ${y}</h2><p>${esc(c)} · ${rows.length} players confirmed in matches</p></div></div>`;$('#teamRoster').innerHTML=rows.map(r=>`<button class="rostercard" data-roster-player="${r.id}"><strong>${esc(r.name)}</strong><small>${r.games} game${r.games===1?'':'s'} · ${esc(c)}</small></button>`).join('');$$('[data-roster-player]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.rosterPlayer));return}if(catalogue.length){$('#teamMeta').innerHTML=`<div class="sectionhead" style="margin-top:26px"><div><h2>${esc(t)} · ${y}</h2><p>${esc(c)} · season player catalogue</p></div></div>`;$('#teamRoster').innerHTML=catalogue.map(r=>{const label=r.appearances?`${r.appearances} season appearance${r.appearances===1?'':'s'}`:'Recorded player';return r.id&&state.players.has(String(r.id))?`<button class="rostercard" data-roster-player="${r.id}"><strong>${esc(r.name)}</strong><small>${label} · match links still being completed</small></button>`:`<div class="rostercard roster-static"><strong>${esc(r.name)}</strong><small>${label} · match links still being completed</small></div>`}).join('');$$('[data-roster-player]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.rosterPlayer));return}const mapped=(TEAM_DIRECTORY[c]?.teams||[]).includes(t);$('#teamMeta').innerHTML=mapped?`<div class="sectionhead" style="margin-top:26px"><div><h2>${esc(t)} · ${esc(y)}</h2><p>${esc(c)} · team mapped</p></div></div>`:'';$('#teamRoster').innerHTML=mapped?'<div class="card empty" style="grid-column:1/-1"><strong>Team mapped.</strong>Its player history is being filled in. Confirmed match appearances will create teammate and opponent links automatically.</div>':'<div class="card empty" style="grid-column:1/-1">No players found for that selection.</div>'};

renderCompetitions=function(){const coverage=new Map();for(const [comp,year,players,teams] of state.catalogueCoverage||[]){const v=coverage.get(comp)||{seasons:0,players:0,teams:0};v.seasons++;v.players+=Number(players||0);v.teams=Math.max(v.teams,Number(teams||0));coverage.set(comp,v)}$('#competitionGrid').innerHTML=COMPETITIONS.map(c=>{const mapped=TEAM_DIRECTORY[c.id]?.teams?.length||0,cat=coverage.get(c.id);let copy,label;if(c.status==='live'){copy='Match-by-match player history is available now.';label='Match history live'}else if(cat){copy=`Season player lists are populated across ${cat.seasons} season${cat.seasons===1?'':'s'}. Match-by-match links are still being completed.`;label='Player lists live'}else if(c.status==='catalogue'){copy='National teams are mapped and can be chosen now. Match-by-match history is being expanded.';label='Teams mapped'}else if(mapped){copy=`${mapped} current teams are mapped. Player and match history is being added.`;label='Teams mapped'}else{copy='Historical teams and player records are being added.';label='Building'}return`<article class="competition-card card"><h3>${esc(c.name)}</h3><p>${copy}</p><div class="meta"><span>${esc(c.years)}</span><span class="comp-status ${c.status}">${label}</span></div></article>`}).join('')};

const llBaseInitUI=initUI;
initUI=function(){llBaseInitUI();ensureOpponents();ensureSeasonCatalogues().then(ok=>{if(!ok)return;fillCompetitionSelect();renderCompetitions();const r=currentRoute();if(r.startsWith('teams'))applyRoute(r);});};
